### ISSUE TITLE
[VIRUS] Virustotal - Detection

### ISSUE THREAD

**Issue by fouquetp** [SatisfactoryFrance/satisfactory_blueprint_manager#74]
Le rapport virus total laisse peu de doute sur le fait qu'il y a un "problème" quelque part !?
https://www.virustotal.com/gui/file/f8a3a9ec8d4678ad57aa1fa20911a572225e8a2b55e732ae5ffd611e534a11a2?nocache=1

**Comment by Allread** [comment]
Bonjour @fouquetp 
En effet, nous avons beaucoup de faux-positif du fait que le logiciel est nouveau (et non signé). 
Nous avons contacté Microsoft afin de whitelist dans Defender mais pas les autres antivirus. 
Mais je peux t'assurer que nous n'essayons pas d'avoir recours à quelquonques trojans ou malwares (aucunes adresses IP bizarres n'est remonté dans le rapport d'ailleurs (que des IP Microsoft) et un ping vers sbm.satisfactoryfr.com à des fins d'analyses d'utilisation du logiciel ☺️

d'ailleurs, la plupart des remontées sont des remontées "génériques" (style Tedy). Cela signifie que la signature est inconnue pour la plupart des A/V (c'est normal, le logiciel est nouveau).
De plus, nous passons par Installforge pour installer le logiciel (ce qui augmente un peu la détection générique mais qui est plus simple à l'utilisation pour la plupart des utilisateurs. 

Les sources sont disponibles donc tu peux fork le repo et lancer toi-même le build du logiciel si besoin :) Nous n'allons pas risquer la communauté si nous ne savons pas ce que nous faisons :)

**Comment by fouquetp** [comment]
Merci pour ce retour, effectivement ça ressemble fort à du faux positif mais vu la quantité sur virustotal je pense qu'il faudrait vraiment le signaler sur github et sur le site web pour ne pas décourager les curieux qui scannent tout ce qu'ils téléchargent... merci pour ce super outil en tout cas ;)

Rock and stones brothers and sisters :D
